#define I2C_WRITE_ADDRESS (0xba)
#define I2C_READ_ADDRESS (0xbb)

///////////////
// REGISTERS //
///////////////
#define CHIP_VERSION_REG (0X00)
#define CHIP_VERSION_REG_PART_ID_MASK (0xff00)
#define CHIP_VERSION_REG_ANALOG_REVISION_MASK (0x00f0)
#define CHIP_VERSION_REG_DIGITAL_REVISION_MASK (0x000f)

#define ROW_START_REG (0x01)

#define COLUMN_START_REG (0x02)

#define ROW_SIZE_REG (0x03)

#define COLUMN_SIZE_REG (0x04)

#define HORIZONTAL_BLANK_REG (0x05)

#define VERTICAL_BLANK_REG (0x06)

#define OUTPUT_CONTROL_REG (0x07)
#define OUTPUT_CONTROL_REG_OUTPUT_SLEW_RATE_MASK (0x1c00)
#define OUTPUT_CONTROL_REG_PIXCLK_SLEW_RATE_MASK (0x0380)
#define OUTPUT_CONTROL_REG_FIFO_PARALLEL_DATA_MASK (0x0004)
#define OUTPUT_CONTROL_REG_CHIP_ENABLE_MASK (0x0002)
#define OUTPUT_CONTROL_REG_SYNCHRONIZE_CHANGES_MASK (0X0001)

#define SHUTTER_WIDTH_UPPER_REG (0x08)

#define SHUTTER_WIDTH_LOWER_REG (0x09)

#define PIXEL_CLOCK_CONTROL_REG (0x0a)
#define PIXEL_CLOCK_CONTROL_REG_INVERT_PIXEL_CLOCK_MASK (0x8000)
#define PIXEL_CLOCK_CONTROL_REG_SHIFT_PIXEL_CLOCK_MASK (0x0700)
#define PIXEL_CLOCK_CONTROL_REG_DIVIDE_PIXEL_CLOCK_MASK (0x007f)

#define RESTART_REG (0x0b)
#define RESTART_REG_TRIGGER_MASK (0x0004)
#define RESTART_REG_PAUSE_RESTART_MASK (0x0002)
#define RESTART_REG_RESTART_MASK (0x0001)

#define SHUTTER_DELAY_REG (0x0c)

#define RESET_REG (0x0d)

#define PLL_CONTROL_REG (0x10)
#define PLL_CONTROL_REG_USE_PLL_MASK (0x0002)
#define PLL_CONTROL_REG_POWER_PLL_MASK (0x0001)

#define PLL_CONFIG_1_REG (0x11)
#define PLL_CONFIG_1_REG_PLL_M_FACTOR_MASK (0xff00)
#define PLL_CONFIG_1_REG_PLL_N_DIVIDER_MASK (0x003f)

#define PLL_CONFIG_2_REG (0x12)
#define PLL_CONFIG_2_REG_PLL_P1_DIVIDER_MASK (0x001f)

#define READ_MODE_1_REG (0x1e)
#define READ_MODE_1_REG_XOR_LINE_VALID_MASK (0x0800)
#define READ_MODE_1_REG_CONTINUOUS_LINE_VALID_MASK (0x0400)
#define READ_MODE_1_REG_INVERT_TRIGGER_MASK (0x0200)
#define READ_MODE_1_REG_SNAPSHOT_MASK (0x0100)
#define READ_MODE_1_REG_GLOBAL_RESET_MASK (0x0080)
#define READ_MODE_1_REG_BULB_EXPOSURE_MASK (0x0040)
#define READ_MODE_1_REG_INVERT_STROBE_MASK (0x0020)
#define READ_MODE_1_REG_STROBE_ENABLE_MASK (0x0010)
#define READ_MODE_1_REG_STROBE_START_MASK (0x000c)
#define READ_MODE_1_REG_STROBE_START_FIRST_TRIGGER (0x0000)
#define READ_MODE_1_REG_STROBE_START_START_OF_SIMULTANEOUS_EXPOSURE (0x0004)
#define READ_MODE_1_REG_STROBE_START_SHUTTER_WIDTH (0x0008)
#define READ_MODE_1_REG_STROBE_START_SECOND_TRIGGER (0x000c)
#define READ_MODE_1_REG_STROBE_END_MASK (0x0003)

#define READ_MODE_2_REG (0x20)
#define READ_MODE_2_REG_MIRROR_ROW_MASK (0x8000)
#define READ_MODE_2_REG_MIRROR_COLUMN_MASK (0x4000)
#define READ_MODE_2_REG_SHOW_DARK_COLUMNS_MASK (0x1000)
#define READ_MODE_2_REG_SHOW_DARK_ROWS_MASK (0x0800)
#define READ_MODE_2_REG_ROW_BLC_MASK (0x0040)
#define READ_MODE_2_REG_COLUMN_SUM_MASK (0x0020)

#define ROW_ADDRESS_MODE_REG (0x22)
#define ROW_ADDRESS_MODE_REG_ROW_BIN_MASK (0x0030)
#define ROW_ADDRESS_MODE_REG_ROW_SKIP_MASK (0x0007)

#define COLUMN_ADDRESS_MODE_REG (0x23)
#define COLUMN_ADDRESS_MODE_REG_COLUMN_BIN_MASK (0x0030)
#define COLUMN_ADDRESS_MODE_REG_COLUMN_SKIP_MASK (0x0007)

#define GREEN_1_GAIN_REG (0x2b)
#define GREEN_1_GAIN_REG_GREEN_1_DIGITAL_GAIN_MASK (0x7f00)
#define GREEN_1_GAIN_REG_GREEN_1_ANALOG_MULTIPLIER_MASK (0x0040)
#define GREEN_1_GAIN_REG_GREEN_1_ANALOG_GAIN_MASK (0x003f)

#define BLUE_GAIN_REG (0x2c)
#define BLUE_GAIN_REG_BLUE_DIGITAL_GAIN_MASK (0x7f00)
#define BLUE_GAIN_REG_BLUE_ANALOG_MULTIPLIER_MASK (0x0040)
#define BLUE_GAIN_REG_BLUE_ANALOG_GAIN_MASK (0x003f)

#define RED_GAIN_REG (0x2d)
#define RED_GAIN_REG_RED_DIGITAL_GAIN_MASK (0x7f00)
#define RED_GAIN_REG_RED_ANALOG_MULTIPLIER_MASK (0x0040)
#define RED_GAIN_REG_RED_ANALOG_GAIN_MASK (0x003f)

#define GREEN_2_GAIN_REG (0x2e)
#define GREEN_2_GAIN_REG_GREEN_2_DIGITAL_GAIN_MASK (0x7f00)
#define GREEN_2_GAIN_REG_GREEN_2_ANALOG_MULTIPLIER_MASK (0x0040)
#define GREEN_2_GAIN_REG_GREEN_2_ANALOG_GAIN_MASK (0x003f)

#define GLOBAL_GAIN_REG (0x35)

#define ROW_BLACK_TARGET_REG (0x49)

#define ROW_BLACK_DEFAULT_OFFSET_REG (0x4b)

#define BLC_SAMPLE_SIZE_REG (0x5b)

#define BLC_TUNE_1_REG (0x5c)
#define BLC_TUNE_1_REG_BLC_DELTA_DAMPING_MASK (0x0f00)
#define BLC_TUNE_1_REG_BLC_DAC_SETTLING_TIME_MASK (0x00ff)

#define BLC_DELTA_THRESHOLDS_REG (0x5d)
#define BLC_DELTA_THRESHOLDS_REG_BLC_HIGH_DELTA_THRESHOLD_MASK (0x7f00)
#define BLC_DELTA_THRESHOLDS_REG_BLC_LOW_DELTA_THRESHOLD_MASK (0x007f)

#define BLC_TUNE_2_REG (0x5e)
#define BLC_TUNE_2_REG_BLC_STEP_SIZE_MASK (0x7000)
#define BLC_TUNE_2_REG_BLC_MAX_ADJUST_MASK (0x01ff)

#define BLC_TARGET_THRESHOLDS_REG (0x5f)
#define BLC_TARGET_THRESHOLDS_REG_BLC_HIGH_TARGET_THRESHOLD_MASK (0x7f00)
#define BLC_TARGET_THRESHOLDS_REG_BLC_LOW_TARGET_THRESHOLD_MASK (0x007f)

#define GREEN_1_OFFSET_REG (0x60)

#define GREEN_2_OFFSET_REG (0x61)

#define BLACK_LEVEL_CALIBRATION_REG (0x62)
#define BLACK_LEVEL_CALIBRATION_REG_DISABLE_FAST_SAMPLE_MASK (0x8000)
#define BLACK_LEVEL_CALIBRATION_REG_LOCK_GREEN_CALIBRATION_MASK (0x4000)
#define BLACK_LEVEL_CALIBRATION_REG_LOCK_RED_BLUE_CALIBRATION_MASK (0x2000)
#define BLACK_LEVEL_CALIBRATION_REG_RECALCULATE_BLACK_LEVEL_MASK (0x1000)
#define BLACK_LEVEL_CALIBRATION_REG_DISABLE_BINARY_SEARCH_MASK (0x0800)
#define BLACK_LEVEL_CALIBRATION_REG_DISABLE_CALIBRATION_MASK (0x0002)
#define BLACK_LEVEL_CALIBRATION_REG_MANUAL_BLC_MASK (0x0001)

#define RED_OFFSET_REG (0x63)

#define BLUE_OFFSET_REG (0x64)

#define TEST_PATTERN_CONTROL_REG (0xa0)
#define TEST_PATTERN_CONTROL_REG_TEST_PATTERN_CONTROL_MASK (0x0078)
#define TEST_PATTERN_CONTROL_REG_TEST_PATTERN_CONTROL_COLOR_FIELD (0x0000)
#define TEST_PATTERN_CONTROL_REG_TEST_PATTERN_CONTROL_HORIZONTAL_GRADIENT (0x0008)
#define TEST_PATTERN_CONTROL_REG_TEST_PATTERN_CONTROL_VERTICAL_GRADIENT (0x0010)
#define TEST_PATTERN_CONTROL_REG_TEST_PATTERN_CONTROL_DIAGONAL (0x0018)
#define TEST_PATTERN_CONTROL_REG_TEST_PATTERN_CONTROL_CLASSIC (0x0020)
#define TEST_PATTERN_CONTROL_REG_TEST_PATTERN_CONTROL_MARCHING_1S (0x0028)
#define TEST_PATTERN_CONTROL_REG_TEST_PATTERN_CONTROL_MONOCHROME_HORIZONTAL_BARS (0x0030)
#define TEST_PATTERN_CONTROL_REG_TEST_PATTERN_CONTROL_MONOCHROME_VERTICAL_BARS (0x0038)
#define TEST_PATTERN_CONTROL_REG_TEST_PATTERN_CONTROL_VERTICAL_COLOR_BARS (0x0040)
#define TEST_PATTERN_CONTROL_REG_ENABLE_TEST_PATTERN_MASK (0x0001)

#define TEST_PATTERN_GREEN_REG (0xa1)

#define TEST_PATTERN_RED_REG (0xa2)

#define TEST_PATTERN_BLUE_REG (0xa3)

#define TEST_PATTERN_BAR_WIDTH_REG (0xa4)

#define CHIP_VERSION_ALT_REG (0xff)
#define CHIP_VERSION_ALT_REG_DIGITAL_REVISION_MASK (0xf000)
#define CHIP_VERSION_ALT_REG_ANALOG_REVISION_MASK (0x0f00)
#define CHIP_VERSION_ALT_REG_PART_ID_MASK (0x00ff)
